auth:
  secret: ${JWT_AUTH_SECRET}
apns:
  team-id: ${APNS_TEAM_ID}
  key-id: ${APNS_KEY_ID}
  bundle-id: ${APNS_BUNDLE_ID}
  auth-key: ${APNS_AUTH_KEY}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name:
      server
